// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWaste.Models;

#nullable disable

namespace SmartWaste.Migrations
{
    [DbContext(typeof(smartwasteContext))]
    [Migration("20260430173251_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartWaste.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SmartWaste.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF6AA4CCE99");

                    b.HasIndex("RequestId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SmartWaste.Models.HubStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sorter");

                    b.HasKey("StaffId")
                        .HasName("PK__HubStaff__96D4AAF74529BE54");

                    b.ToTable("HubStaff", (string)null);
                });

            modelBuilder.Entity("SmartWaste.Models.PickupRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("EstimatedPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("FinalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("HubStaffId")
                        .HasColumnType("int")
                        .HasColumnName("HubStaffID");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QRCode");

                    b.Property<int?>("RecyclerId")
                        .HasColumnType("int")
                        .HasColumnName("RecyclerID");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("RequestId")
                        .HasName("PK__PickupRe__33A8519AFA03C46A");

                    b.HasIndex("HubStaffId");

                    b.HasIndex("RecyclerId");

                    b.HasIndex("UserId");

                    b.ToTable("PickupRequests");
                });

            modelBuilder.Entity("SmartWaste.Models.Recycler", b =>
                {
                    b.Property<int>("RecyclerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecyclerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecyclerId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(5.0m);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Offline");

                    b.Property<string>("VehicleInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecyclerId")
                        .HasName("PK__Recycler__CF8A55D5FEB653EF");

                    b.HasIndex(new[] { "Phone" }, "UQ__Recycler__5C7E359E9AF9A312")
                        .IsUnique();

                    b.ToTable("Recyclers");
                });

            modelBuilder.Entity("SmartWaste.Models.RequestItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemId")
                        .HasName("PK__RequestI__727E83EB51E2336E");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestItems");
                });

            modelBuilder.Entity("SmartWaste.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<decimal>("CostPoints")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RewardId")
                        .HasName("PK__Rewards__8250159966275F67");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("SmartWaste.Models.SupportTickets", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TicketID");

                    b.HasIndex("CitizenID");

                    b.HasIndex("DriverID");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("SmartWaste.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WalletPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.0m);

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC6EBB6AB5");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AFF072C8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartWaste.Models.UserRedemption", b =>
                {
                    b.Property<int>("RedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RedemptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RedemptionId"));

                    b.Property<DateTime?>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RedemptionId")
                        .HasName("PK__UserRede__410680D10B55621C");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRedemptions");
                });

            modelBuilder.Entity("SmartWaste.Models.WasteCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PointsPerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Item");

                    b.HasKey("CategoryId")
                        .HasName("PK__WasteCat__19093A2BB1FAC898");

                    b.ToTable("WasteCategories");
                });

            modelBuilder.Entity("SmartWaste.Models.Feedback", b =>
                {
                    b.HasOne("SmartWaste.Models.PickupRequest", "Request")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Request");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SmartWaste.Models.PickupRequest", b =>
                {
                    b.HasOne("SmartWaste.Models.HubStaff", "HubStaff")
                        .WithMany("PickupRequests")
                        .HasForeignKey("HubStaffId")
                        .HasConstraintName("FK_Requests_Staff");

                    b.HasOne("SmartWaste.Models.Recycler", "Recycler")
                        .WithMany("PickupRequests")
                        .HasForeignKey("RecyclerId")
                        .HasConstraintName("FK_Requests_Recycler");

                    b.HasOne("SmartWaste.Models.User", "User")
                        .WithMany("PickupRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_User");

                    b.Navigation("HubStaff");

                    b.Navigation("Recycler");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartWaste.Models.RequestItem", b =>
                {
                    b.HasOne("SmartWaste.Models.WasteCategory", "Category")
                        .WithMany("RequestItems")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Items_Category");

                    b.HasOne("SmartWaste.Models.PickupRequest", "Request")
                        .WithMany("RequestItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Items_Request");

                    b.Navigation("Category");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SmartWaste.Models.SupportTickets", b =>
                {
                    b.HasOne("SmartWaste.Models.User", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartWaste.Models.Recycler", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.Navigation("Citizen");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SmartWaste.Models.UserRedemption", b =>
                {
                    b.HasOne("SmartWaste.Models.Reward", "Reward")
                        .WithMany("UserRedemptions")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("FK_Redemption_Reward");

                    b.HasOne("SmartWaste.Models.User", "User")
                        .WithMany("UserRedemptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Redemption_User");

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartWaste.Models.HubStaff", b =>
                {
                    b.Navigation("PickupRequests");
                });

            modelBuilder.Entity("SmartWaste.Models.PickupRequest", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("SmartWaste.Models.Recycler", b =>
                {
                    b.Navigation("PickupRequests");
                });

            modelBuilder.Entity("SmartWaste.Models.Reward", b =>
                {
                    b.Navigation("UserRedemptions");
                });

            modelBuilder.Entity("SmartWaste.Models.User", b =>
                {
                    b.Navigation("PickupRequests");

                    b.Navigation("UserRedemptions");
                });

            modelBuilder.Entity("SmartWaste.Models.WasteCategory", b =>
                {
                    b.Navigation("RequestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
